package initx

// AIContextFile은 생성될 AI context 파일 하나를 나타낸다.
type AIContextFile struct {
	Path    string // 상대 경로 (예: "CLAUDE.md")
	Content string // 생성된 내용
}

// AIContextOptions는 AI context 생성 옵션이다.
type AIContextOptions struct {
	IncludeKiro bool // .kiro/steering/* 파일도 생성할지
}

// GenerateAIContext는 프로젝트 분석 결과를 template에 주입하여
// AI context 파일 내용을 생성한다.
// IncludeKiro=true 시 .kiro/steering/ 파일 3개를 생성한다.
// CLAUDE.md, AGENTS.md는 AI 코딩 어시스턴트가 자동 생성하므로 포함하지 않는다.
func GenerateAIContext(result *AnalysisResult, opts AIContextOptions) []AIContextFile {
	var files []AIContextFile

	if opts.IncludeKiro {
		files = append(files,
			AIContextFile{Path: ".kiro/steering/product.md", Content: kiroProductTemplate},
			AIContextFile{Path: ".kiro/steering/tech.md", Content: kiroTechTemplate},
			AIContextFile{Path: ".kiro/steering/structure.md", Content: kiroStructureTemplate},
		)
	}

	return files
}

// bt is a backtick character, used to embed backticks inside raw string literals.
const bt = "`"

// Template constants — internal/cli/templates/ai/ 파일 내용과 동일.
// Go embed는 같은 패키지 디렉토리에서만 동작하므로 상수로 정의한다.

var kiroProductTemplate = `---
inclusion: always
---
# Product Overview

## What this product is
<!-- TODO: One sentence description of the product and its core value -->
<!-- Example: "A CLI tool that streamlines Git workflows for developer teams." -->

## Target users
<!-- TODO: Who uses this product and what problem does it solve for them? -->
<!-- Example: "Developers who want safer, faster Git operations without memorizing flags." -->

## Core goals
- <!-- TODO: Primary goal — the single most important outcome this product must achieve -->
- <!-- TODO: Secondary goal -->
- <!-- TODO: Non-goal: what this product deliberately does NOT do -->

## Key features
<!-- TODO: List the major capabilities. One line each. -->
- Feature 1: ...
- Feature 2: ...
- Feature 3: ...

## Success criteria
<!-- TODO: How do you know the product is working? Metrics, user signals, etc. -->
- ...

## Out of scope
<!-- TODO: Explicitly list what this product will never do, to prevent scope creep -->
- ...
`

var kiroTechTemplate = `---
inclusion: always
---
# Tech Stack & Architecture

## Language & runtime
<!-- TODO: Primary language and version, e.g. "Go 1.24", "Node 22 (ESM)", "Python 3.12" -->

## Key dependencies
<!-- TODO: List major libraries/frameworks with a one-line rationale for each -->
| Package | Purpose |
|---------|---------|
| <!-- dep --> | <!-- why --> |

## Architecture style
<!-- TODO: e.g. "Layered CLI (cmd → internal → pkg)", "Hexagonal", "Monolith", "Microservices" -->

## Directory conventions
<!-- TODO: Describe which code lives where and why -->
- ` + bt + `cmd/` + bt + ` — entry points only; no business logic
- ` + bt + `internal/` + bt + ` — private application code
- ` + bt + `pkg/` + bt + ` — reusable packages safe to import externally

## Build & tooling
<!-- TODO: How to build, test, lint -->
- Build: ` + bt + `<!-- e.g. go build ./... -->` + bt + `
- Test:  ` + bt + `<!-- e.g. go test ./... -->` + bt + `
- Lint:  ` + bt + `<!-- e.g. golangci-lint run -->` + bt + `

## Key architectural decisions
<!-- TODO: Document non-obvious choices the AI must respect -->
- **Decision 1**: <!-- What was decided and why; what was rejected -->
- **Decision 2**: ...

## Coding standards
<!-- TODO: Style rules, naming conventions, error-handling patterns, etc. -->
- Error handling: ...
- Naming: ...
- Testing: ...

## Environment & configuration
<!-- TODO: How is the app configured? Env vars, config files, flags? -->
- Config file: ...
- Required env vars: ...
`

var kiroStructureTemplate = `---
inclusion: always
---
# Repository Structure

## Top-level layout
` + bt + bt + bt + `
.
├── cmd/            # Executable entry points
├── internal/       # Private application packages
├── pkg/            # Public reusable packages
├── docs/           # Documentation
├── testdata/       # Fixtures and golden files
└── <!-- TODO: add/remove directories to match your repo -->
` + bt + bt + bt + `

## Key files
<!-- TODO: List files the AI must know about to navigate this codebase effectively -->
| File / Dir | Role |
|-----------|------|
| ` + bt + `<!-- path -->` + bt + ` | <!-- what it does --> |

## Where to put new code
<!-- TODO: Decision rules for where new logic belongs -->
- New CLI command → ` + bt + `<!-- e.g. internal/cli/<command>.go -->` + bt + `
- New business logic → ` + bt + `<!-- e.g. internal/<package>/ -->` + bt + `
- New shared utility → ` + bt + `<!-- e.g. pkg/<package>/ -->` + bt + `
- Tests → alongside the file they test, ` + bt + `_test.go` + bt + ` suffix

## Generated files
<!-- TODO: List any files that are auto-generated and must NOT be edited by hand -->
- ` + bt + `<!-- file -->` + bt + ` — generated by ` + bt + `<!-- tool -->` + bt + `; edit ` + bt + `<!-- source -->` + bt + ` instead

## Naming conventions
<!-- TODO: File, package, and symbol naming rules -->
- Files: ` + bt + `snake_case.go` + bt + `
- Packages: short, lowercase, no underscores
- Exported types: ` + bt + `PascalCase` + bt + `; unexported: ` + bt + `camelCase` + bt + `

## Module / package boundaries
<!-- TODO: Describe import rules, forbidden dependencies, layering constraints -->
- ` + bt + `internal/cli` + bt + ` may import ` + bt + `internal/*` + bt + ` and ` + bt + `pkg/*` + bt + `
- ` + bt + `pkg/*` + bt + ` must NOT import ` + bt + `internal/*` + bt + `
- <!-- TODO: other rules -->
`
