package cli

// help_easy_data.go — plain-Korean Long descriptions and command-local
// flag help, produced by parallel translation agents and integrated. The
// swap-on-render mechanism lives in help_easy.go; this file fills the maps.
// Regenerate by re-running the translate-gk-help workflow.

func init() {
	easyLongKO = map[string]string{
		"gk commit":                   "현재 작업 내용의 변경(준비됨+준비 안 됨+새 파일)을 분석해 의미 단위로 묶고, AI를 이용해 Conventional Commit 형식 메시지로 커밋한다.\n\nAI 제공자 결정 순서:\n  1. --provider 옵션\n  2. .gk.yaml / config.yaml의 ai.provider\n  3. 자동 감지(gemini → qwen → kiro-cli)\n\n기본은 대화형 화면에서 검토하는 방식이며, --force/-f를 주면 검토를 건너뛴다.\n\n--dry-run은 묶음 계획과 묶음별 예상 토큰 비용만 보여주고 AI 호출은 하지 않는다. 큰 작업 전 미리 확인할 때 유용하며, 하루 토큰 한도를 다 써도 동작한다.\n\n--abort를 쓰면 가장 최근 실행 시작 시 만들어 둔 백업 지점으로 HEAD를 되돌린다.",
		"gk pull":                     "원격(upstream)에서 변경을 가져와 현재 브랜치에 합친다.\n\n방식 결정 순서(먼저 맞는 것 적용):\n  1. --strategy 옵션\n  2. .gk.yaml의 pull.strategy\n  3. git 설정 pull.rebase (true→재정렬(rebase), false→병합(merge))\n  4. 기본: 재정렬(rebase)\n\n원격 위치 결정:\n  현재 브랜치가 원격 브랜치(@{u})를 따라가면 그 원격을 사용. 아니면 <remote>/<기준 브랜치>를 대신 사용.\n\n빨리 감기(fast-forward) 최적화:\n  재정렬 방식이고 HEAD가 이미 원격의 이전 지점이면, gk는 git merge --ff-only로 대체한다 — 결과는 같고 재정렬 부담이 없다.\n\n기준 브랜치 함께 동기화:\n  --with-base(또는 .gk.yaml의 pull.with_base: true)를 주면 가져온 뒤 로컬 기준 브랜치(main 등)도 원격 끝으로 빨리 감기한다 — 체크아웃 없이. 엄격히 빨리 감기만 한다: 갈라졌거나, 다른 worktree에 체크아웃돼 있거나, 로컬에 브랜치가 없으면 자동 처리 대신 NOTE와 함께 건너뛴다. --fetch-only일 때는 수행하지 않는다.",
		"gk sync":                     "로컬 기준 브랜치(base)를 현재 브랜치에 합친다. 기본적으로 로컬 기록만 다루며 네트워크를 쓰지 않는다. 현재 브랜치가 이미 <base>의 이전 지점이면 빨리 감기(fast-forward)하고, 아니면 재정렬(rebase)한다(설정 변경 가능).\n\n이것은 gk의 pull/sync 분리에서 '기준 브랜치 기준 재정렬'을 담당하는 쪽이다:\n\n  gk pull  ← 네트워크: <remote>/<자기 브랜치>를 가져와 합침\n  gk sync  ← 로컬: HEAD를 로컬 <base> 위로 재정렬\n\n로컬 <base>를 원격에서 먼저 새로고침하려면:\n  gk checkout <base> && gk pull  (명시적 두 단계)\n  gk sync --fetch                (가져오기 + 로컬 <base> 빨리 감기 + 합치기)\n\n방식 결정 순서(먼저 맞는 것 적용):\n  1. --strategy 옵션\n  2. .gk.yaml의 sync.strategy\n  3. git 설정 pull.rebase (true→재정렬, false→병합)\n  4. 기본: 재정렬(rebase)\n\n자기 브랜치 빨리 감기: origin/<자기 브랜치>가 로컬 브랜치보다 확실히 앞서 있으면(예: 다른 컴퓨터에서 먼저 푸시함) base를 합치기 전에 빨리 감기한다. 기록이 갈라진 경우엔 조용히 건너뛴다.\n\n로컬 <base>가 <remote>/<base>와 다르면 안내만 하고 막지는 않는다 — 사용자가 '로컬 <base> 기준'을 명시적으로 요청했기 때문이다.\n\n옛 방식: --upstream-only는 v0.6 sync 동작(가져오기 + origin/<자기 브랜치>로만 빨리 감기, base는 절대 합치지 않음)을 한 번 더 유지한다. v0.8에서 제거되며 gk pull이 같은 기능을 한다.\n\n종료 코드:\n  0  합치기 성공 또는 이미 최신\n  1  일반 오류(로컬 base 없음, --autostash 없이 변경이 남아 있음 등)\n  3  재정렬/병합 충돌(gk continue / gk abort로 이어서 처리)\n  4  기록이 갈라졌으나 --strategy ff-only가 이를 거부함",
		"gk merge":                    "git merge를 실행하기 전에 합치기 테스트를 먼저 돌려 충돌이 없는지 점검.\n\n방향은 git merge와 동일. gk merge <대상>은 <대상>을 현재 브랜치로 합침. 현재 브랜치를 <대상>에 넣는 것이 아님.\n\n현재 브랜치를 다른 작업 폴더(worktree)에 체크아웃된 브랜치로 합치려면 gk merge --into <브랜치> 사용. <브랜치>의 작업 폴더를 찾아 현재 브랜치를 그곳에 합침.\n\n기본적으로 git이 추적 중인 작업 폴더 변경 사항이 있으면 gk는 시작을 거부. --autostash를 쓰면 합치기 전에 변경 사항을 임시 보관(stash)했다가 끝난 뒤 되돌림.",
		"gk next":                     "현재 저장소 상태를 읽고 다음에 무엇을 할지 쉬운 말로 설명. 설정된 AI 제공자가 있으면 그것을 쓰고, 없으면 정해진 규칙에 따른 안내로 대체.\n\n--run을 쓰면 gk가 추천하는 다음 단계 하나(gk가 허용한 정해진 동작 목록에서 고른 것이며, AI가 자유롭게 만들어낸 것이 아님)를 실행할지 물어본 뒤 확인하면 실행. 위험한 명령은 절대 자동 실행하지 않음.",
		"gk guide":                    "일반적인 git 작업 흐름을 단계별로 안내. 작업 흐름 이름을 인자로 넘기면 메뉴를 건너뛰고 바로 시작.",
		"gk branch set-parent":        "`branch.<현재브랜치>.gk-parent = <부모브랜치>` 값을 기록. 이렇게 하면 `gk status` 같은 명령이 차이를 비교할 때 저장소의 기본 줄기 브랜치가 아니라 실제 부모 브랜치를 기준으로 비교. 어떤 기능 브랜치가 main이 아니라 다른 기능 브랜치에서 갈라져 나온 쌓기(stacked) 작업 흐름에서 유용.\n\n저장 전 검사 항목:\n  - 부모는 비어 있지 않은 로컬 브랜치 이름이어야 함\n  - 부모와 현재 브랜치가 같으면 안 됨(자기 자신을 부모로 지정 불가)\n  - 부모는 원격 추적용 이름(예: origin/main)이면 안 됨\n  - 부모는 실제로 존재하는 로컬 브랜치여야 함(태그 불가)\n  - 부모를 지정해도 순환(서로가 서로의 부모)이 생기면 안 되고, 이어지는 부모 사슬은 최대 10단계까지만 허용\n\n지정한 부모가 존재하지 않으면 가장 비슷한 로컬 브랜치 이름을 제안(철자 유사도 기반)하여 흔한 오타를 잡아줌.",
		"gk branch unset-parent":      "git 설정에서 `branch.<현재브랜치>.gk-parent` 값을 제거. 여러 번 실행해도 안전: 부모가 지정되지 않은 브랜치에서 실행해도 조용히 성공. 다음 실행부터 status 출력이 기준(base) 브랜치 대비 차이로 되돌아감.",
		"gk branch-check":             "현재 브랜치(또는 지정한 브랜치) 이름이 `branch.patterns`에 설정된 패턴에 맞는지 검사. 보호 브랜치(`branch.protected`)는 패턴 검사 없이 항상 허용.\n\n성공 시 종료 코드 0, 실패 시 0이 아닌 값(cobra 기본값).\n\nprepare-commit-msg 훅으로 쓰는 예시:\n  gk branch-check",
		"gk worktree":                 "작업 폴더(worktree) 관리 도구 모음.\n\n하위 명령 없이 실행하면 worktree를 목록 보기, 추가, 삭제, 들어가기 할 수 있는 대화형 화면(TUI)이 열림. worktree를 고르면 해당 폴더에서 새 $SHELL이 실행됨 — 'exit'을 입력하면 원래 셸로 돌아옴.\n\n폴더를 그 자리에서 바꾸는(cd) 방식을 원하면 --print-path를 붙이고 셸 별칭으로 감싸 선택한 경로가 상위 셸에 적용되도록 함:\n\n    # ~/.zshrc 또는 ~/.bashrc\n    gwt() { local p=\"$(gk wt --print-path)\"; [ -n \"$p\" ] && cd \"$p\"; }\n\n입력/출력이 대화형이 아닐 때는 TUI 대신 이 도움말을 출력.",
		"gk worktree add":             "worktree를 생성.\n\n경로 결정 방식:\n  - 절대 경로는 그대로 사용.\n  - 상대 이름/경로는 관리용 기본 폴더 아래에 만들어짐:\n      <worktree.base>/<worktree.project>/<name>\n    기본 base는 ~/.gk/worktree, project는 저장소 최상위 폴더 이름이 기본값. 둘 다 .gk.yaml에서 바꿀 수 있음.\n\n브랜치 처리:\n  - --new 없이 쓰면 [branch]가 이미 존재해야 함(로컬 또는 원격 추적).\n  - --new(-b)와 함께 쓰면 --from(기본값 HEAD)에서 [branch] 이름의 새 브랜치를 생성.\n\n예시:\n  gk worktree add ai-commit           # ~/.gk/worktree/<project>/ai-commit\n  gk worktree add feat-x -b feat/x    # 새 브랜치, 관리용 경로\n  gk worktree add /tmp/exp -b hotfix  # 절대 경로 우선, 브랜치는 그래도 생성",
		"gk precheck":                 "합치기 전 충돌 예보(별칭 forecast): 지금 위치(HEAD)와 대상을 미리 합쳐보고 충돌날 파일들을 보여줌. 대상을 생략하면 다음 pull(추적 원격, 없으면 기준 브랜치) 기준. 실제 작업 내용, 임시 저장 영역, 브랜치 정보는 전혀 바뀌지 않음.\n\n종료 코드:\n  0  충돌 없이 깔끔하게 합쳐짐\n  2  잘못된 입력(없는 대상, 잘못된 인자)\n  3  충돌 발견\n\ngit 2.40 이상 필요(--name-only 기능). 더 낮은 버전에서는 충돌 표시 기호를 직접 분석하는 방식으로 대체됨.",
		"gk rebase":                   "커밋 기록 정리를 편집기 없이 계획서(JSON)로 처리. git rebase -i를 열면 나오는 편집 화면 대신, 커밋마다 무엇을 할지 적은 계획서를 주고받는 방식이라 사람도 스크립트도 AI도 같은 절차를 쓴다.\n\n진행 순서:\n  1. gk rebase --plan-template    # 정리 대상 커밋 목록을 계획서 초안으로 받음\n  2. 커밋별 action을 정함          # pick(유지) / squash(앞 커밋에 합침) / fixup(합치고 메시지 버림) / reword(메시지 수정) / drop(삭제)\n  3. gk rebase --plan - < 계획서   # 검사 후 실행\n\n안전장치:\n  - 범위 안 모든 커밋을 계획서가 빠짐없이 다뤄야 함(빼먹으면 에러 — 지우려면 drop을 명시)\n  - 서버(원격)에 이미 올라간 커밋을 고치는 계획은 거부(--allow-pushed로만 허용)\n  - 실행 전 백업 지점(refs/gk/backup/...)을 만들어 둠\n  - 충돌이 나면 멈추고 gk continue / gk abort로 이어감\n\n--dry-run은 실제로 바꾸지 않고 무엇이 실행될지만 보여줌.",
		"gk reset":                    "현재 브랜치의 원격 저장소 내용을 받아온 뒤, 작업 내용을 그 상태로 강제로 되돌림.\n\n되돌릴 수 없는 작업 — 저장하지 않은 변경이나 원격보다 앞서 있는 로컬 커밋은 모두 사라짐. --dry-run이 아니면 터미널에서 직접 확인하거나 --yes가 필요함.\n\n예시:\n  gk reset                         # 연결된 원격 브랜치 상태로 되돌리기\n  gk reset main                    # main 상태로 되돌리기 (--to main 과 동일)\n  gk reset --to-remote             # <원격>/<현재 브랜치> 상태로 되돌리기 (연결된 원격 무시)\n  gk reset --to origin/main        # 특정 위치로 되돌리기\n  gk reset --yes --clean           # 확인 없이, 추적 안 되는 파일까지 함께 삭제",
		"gk refresh":                  "로컬에 오래 유지하는 브랜치들을 각자의 원격 브랜치 상태에 맞춰 따라가게 함.\n\n각 브랜치는 origin/<브랜치>로 독립적으로 빨리감기(fast-forward)됨 — refresh는 브랜치끼리 재정렬(rebase)하거나 합치지(merge) 않음. 브랜치는 오직 자기 원격으로만, 그것도 빨리감기 방식으로만 이동하므로 공용 브랜치에서도 안전함:\n\n  main    ←ff──  origin/main\n  develop ←ff──  origin/develop\n\n이 명령은 'main으로 옮기고 pull, develop으로 옮기고 pull' 같은 수작업을 한 번에 처리하며, 현재 위치를 떠나지 않음: 지금 서 있지 않은 브랜치는 작업 내용을 건드리지 않고 위치 정보만 갱신하므로, 변경사항이 있는 기능 브랜치에서도 동작함.\n\n대상 결정 순서:\n  1. 직접 입력한 인자     (gk refresh main release/1.x)\n  2. .gk.yaml 의 refresh.tracked\n  3. 자동: 로컬에 있는 main/master 와 develop/dev\n\n원격과 갈라진(원격에 없는 로컬 커밋이 있는) 브랜치는 건드리지 않고 안내와 함께 건너뜀 — 그 경우엔 'gk pull' 사용.\n\n종료 코드:\n  0  해결 가능한 모든 브랜치가 최신이거나 빨리감기됨\n  1  일반 오류(대상 없음, 받아오기 실패에 저장된 정보도 없음)",
		"gk clone":                    "gk clone은 짧게 입력한 값을 git 주소로 펼친 뒤 git clone에 넘기므로, 전체 호스트나 프로토콜을 거의 입력하지 않아도 됨:\n\n  gk clone JINWOO-J/playground        # git@github.com:JINWOO-J/playground.git\n  gk clone JINWOO-J/playground --https # https://github.com/...\n  gk clone gl:group/service            # clone.hosts 에서 'gl' 해석\n  gk clone https://example.com/x/y     # 완전한 주소는 그대로 사용\n  gk clone git@host:x/y.git            # SCP 형식 주소도 그대로 사용\n\n설정 키(.gk.yaml):\n\n  clone:\n    default_protocol: ssh       # 또는 https\n    default_host: github.com\n    root: ~/work                # 선택, Go 스타일 폴더 구조: <root>/<host>/<owner>/<repo>\n    hosts:\n      gl: { host: gitlab.com, protocol: ssh }\n      work: { host: git.company.internal, protocol: https }\n    post_actions: [hooks-install, doctor]\n\n--dry-run을 쓰면 해석된 주소와 대상 위치만 출력하고 네트워크는 건드리지 않은 채 종료.",
		"gk stash":                    "임시 저장(stash) 목록을 살펴보고 작업함.\n\n하위 명령 없이 실행하면 대화형 선택 화면이 열림:\n  - 임시 저장 항목을 고른 뒤 적용(apply) / 꺼내기(pop) / 보기(show) / 버리기(drop).\n\n하위 명령:\n  push   새 임시 저장 만들기 (--include-untracked 선택)\n  list   임시 저장 표 출력 (선택 화면과 동일)\n  pop    참조로 임시 저장을 적용한 뒤 삭제 (기본: stash@{0})\n  apply  삭제하지 않고 적용만\n  drop   임시 저장 버리기",
		"gk wip":                      "작업 내용을 잃지 않고 다른 일로 잠시 넘어갈 수 있도록 임시 저장 커밋을 만듦.\n\ngit이 추적 중인 모든 변경(삭제된 파일 포함)을 담아 \"--wip-- [skip ci]\" 제목으로 커밋. 이 커밋은 검사 훅(hook)과 서명을 건너뛰어(--no-verify, --no-gpg-sign) 빠르고 되돌리기 쉬움. 나중에 'gk unwip'으로 커밋만 풀어 변경 내용을 다시 꺼낼 수 있음.",
		"gk unwip":                    "현재 위치(HEAD)의 커밋 제목이 '--wip--'로 시작하면 'git reset HEAD~1'로 그 커밋을 풀어 변경 내용을 작업 폴더로 되돌림. '--wip--' 임시 저장 커밋이 아니면 동작하지 않음.",
		"gk snapshot":                 "작업 폴더 상태를 잃지 않게 그림자 보관소(refs/wip/<브랜치>)에 안전망 스냅샷으로 저장.\n\n'gk wip'과 달리 브랜치 기록에는 아무것도 커밋하지 않음 — 작업 폴더·스테이지·커밋 기록을 전혀 건드리지 않고, 추적 파일 변경과 추적 안 되던 새 파일(.gitignore 존중)까지 그대로 떠둠. 이 스냅샷은 'git branch'에 안 보이고, push되지 않으며, 'git gc'에도 살아남음. 그 ref의 작업 기록(reflog)이 곧 스냅샷 이력.\n\n자동 안전망으로 쓰기 좋음(예: Claude Code Stop 훅에서 'gk snapshot -q').\n\n예시:\n  gk snapshot              # 지금 작업 폴더를 스냅샷\n  gk snapshot -m \"메모\"     # 메모를 달아 저장\n  gk snapshots             # 이 브랜치의 스냅샷 목록\n  gk snapshot restore      # 가장 최근 스냅샷 복원\n  gk snapshot restore 2    # 더 오래된 스냅샷 복원",
		"gk snapshots":                "현재 브랜치의 안전망 스냅샷을 시간순으로 나열(= 'gk snapshot list'). 각 줄의 @{n} 번호를 'gk snapshot restore n'에 그대로 쓸 수 있음.",
		"gk snapshot list":            "현재 브랜치의 안전망 스냅샷 목록을 출력. 각 항목은 @{n} 번호, 저장된 상대 시각, 메모를 보여줌.",
		"gk snapshot restore":         "스냅샷 n번(생략 시 0 = 가장 최근)을 작업 폴더와 스테이지로 복원.\n\n작업 폴더에 저장 안 한 변경이 있으면, 먼저 그 상태를 새 스냅샷으로 떠두어 아무것도 잃지 않음. 지금 있지만 스냅샷에는 없는 파일은 건드리지 않고 그대로 둠.",
		"gk wipe":                     "현재 위치(HEAD)를 강제로 되돌리고 'git clean -fd'를 실행해 작업 폴더를 깨끗이 비움.\n\n되돌릴 수 없는 작업 — 저장(커밋)하지 않은 변경과 git이 추적하지 않는 파일이 사라짐. 비우기 직전 위치를 가리키는 백업 표식이 refs/gk/wipe-backup/<브랜치>/<시각>에 만들어져 로컬 커밋은 다시 복구 가능(추적하지 않던 파일은 복구 불가). 진행하려면 터미널에서 직접 확인하거나 --yes 필요.\n\n예시:\n  gk wipe --dry-run          # 무엇이 지워질지 미리 보기\n  gk wipe --yes              # 확인 없이 강제 되돌리기 + 폴더 비우기\n  gk wipe --include-ignored  # .gitignore로 무시되던 파일까지 함께 삭제",
		"gk forget":                   "저장소의 모든 커밋(과거 기록 포함)에서 지정한 파일/폴더를 완전히 지운다. 두 가지 방식이 있다: 기본 native는 gk에 내장된 방식(설치 불필요), --engine filter-repo는 git filter-repo에 맡기는 방식(별도 설치 필요)이다. .gk.yaml의 forget.engine으로 기본 방식을 바꿀 수 있다(옵션이 우선).\n\n경로를 지정하지 않으면, 이미 .gitignore에 등록되어 있는데도 git이 추적 중인 파일을 자동으로 찾아낸다. 즉 다음 작업\n\n  echo db/ >> .gitignore\n  gk forget\n\n처럼, .gitignore 규칙이 생기기 전에 이미 커밋된 파일을 한 줄로 정리할 수 있다.\n\n되돌릴 수 없는 작업 — 모든 커밋의 식별값(SHA)이 바뀐다. 기록을 다시 쓴 뒤에는 함께 작업하는 사람들이 저장소를 새로 받거나(re-clone) 강제로 맞춰야(hard-reset) 한다. 작업 전에 백업이 refs/gk/forget-backup/<브랜치>/<시각> 에 저장되며(`gk timemachine list`에서 확인 가능), .git/gk/forget-backup-<시각>.txt 에 텍스트 목록도 남는다. 옛 기록의 데이터는 지우지 않고 남겨두므로 이 백업으로 정말 되돌릴 수 있다 — 용량 회수는 결과가 확실해진 뒤 git gc --prune=now 로 직접 한다.\n\n저장 안 한 변경이 있을 때: 지우려는 대상 경로 안의 변경은 어차피 함께 사라지므로 문제없다. 대상 밖의 변경이 있으면 작업을 멈추고 안내한다(기록 재작성이 그 변경을 조용히 날려버리기 때문). 대상 밖 변경을 직접 확인했고 잃어도 괜찮다면 --force-dirty를 붙인다.\n\n기본 native 방식은 별도 설치가 필요 없다. --engine filter-repo는 git filter-repo가 필요하다 (https://github.com/newren/git-filter-repo). 설치: brew install git-filter-repo (또는 pip install git-filter-repo).\n\n예시:\n  gk forget                              # .gitignore에 있는데도 추적 중인 파일 자동 탐지\n  gk forget db/ secrets.json             # 경로 직접 지정\n  gk forget --dry-run db/                # 실제 변경 없이 미리보기\n  gk forget --yes db/                    # 확인 질문 건너뛰기\n  gk forget --analyze db/                # db/가 차지하는 용량 정확히 추정\n  gk forget --analyze                    # 저장소 전체 점검(용량 큰 최상위 폴더)\n  gk forget --analyze --depth 2          # 저장소 전체 점검, 경로 두 단계로 묶기\n  gk forget --analyze --depth 0 --top 50 # 용량 큰 개별 파일 50개\n  gk forget db/ --keep \"db/keep/*\"       # db/는 지우되 db/keep/ 항목은 남기기\n  gk forget db/ --engine filter-repo     # git filter-repo에 맡기는 방식 사용",
		"gk undo":                     "git 작업 기록(reflog)을 읽어, 과거 상태 중 하나를 고르면 백업을 먼저 남긴 뒤 그 시점으로 되돌린다.\n\n되돌리는 방식:\n  기본값  --mixed  현재 위치(HEAD)만 그 시점으로 옮기고, 파일 내용은 그대로 둠\n                    (편집 내용은 '저장 대기 해제' 상태로 남음 — 데이터 손실 없음)\n  --hard           현재 위치와 함께 파일 내용까지 그 시점으로 되돌림\n                    (그 시점의 편집 내용이 복원되고, 지금 편집한 내용은 사라짐)\n\n정말 \"그 순간으로 완전히 돌아가고\" 싶을 때 --hard를 쓴다. 기본값은 안전한 쪽으로 동작한다.",
		"gk timemachine":              "timemachine은 되살릴 수 있는 과거 상태를 모두 보여준다 — 작업 기록(reflog), gk undo/wipe가 남긴 백업, 그리고 (선택 시) 어디에도 연결되지 않은 커밋까지 — 그리고 그중 아무거나 안전하게 되돌릴 수 있게 해준다. 되돌릴 때마다 먼저 새 백업을 남기므로, 작업은 언제든 다시 되돌릴 수 있다.\n\n이 기능은 단계적으로 출시된다. v0.7에서 restore 하위 명령이 추가되고, 대화형 화면(TUI)과 list --json 출력은 그 뒤에 나온다.",
		"gk timemachine list":         "현재 위치(HEAD)의 작업 기록, 선택 시 브랜치별 작업 기록, 그리고 gk가 남긴 모든 백업을 하나의 시간 순서 목록으로 합쳐서 보여준다. --kinds로 보여줄 종류를 거를 수 있고, --json으로 스크립트에서 쓰기 좋은 NDJSON 형식으로 받을 수 있다.",
		"gk timemachine list-backups": "gk undo / gk wipe / gk timemachine restore가 만든 모든 백업을 보여준다. 각 항목은 `gk timemachine restore <ref>`로 되돌릴 수 있다.\n\n--json을 쓰면 한 줄에 NDJSON 객체 하나씩 출력되어 jq로 넘기기 좋다.",
		"gk timemachine restore":      "restore는 현재 끝 지점에 백업을 먼저 남긴 뒤, 현재 위치(HEAD)를 지정한 커밋으로 옮긴다. 중간에 실패하면 백업 위치를 출력하므로, 되돌리기 전 상태로 항상 돌아갈 수 있다.\n\n  --mode soft|mixed|hard|auto   되돌리는 방식 (기본값: auto — DecideStrategy가 자동 선택)\n  --dry-run                     계획만 출력하고 종료. 저장소는 건드리지 않음\n  --autostash                   작업 중 변경이 있으면 잠시 따로 보관(stash)했다가 되돌린 뒤 다시 꺼냄\n  --force                       작업 중 변경이 있어도 따로 보관 없이 hard 방식 허용(데이터 손실)",
		"gk timemachine show":         "지정한 커밋 식별값(SHA)이나 ref를 git rev-parse로 확인하고, gk가 남긴 백업 정보가 있으면 함께 찾아 다음을 출력한다:\n\n  * 확인된 SHA + 커밋 제목 + 작성자 + 날짜\n  * 그 ref가 gk 백업이면, 백업 설명(종류, 브랜치, 시각)\n  * git show --stat <sha> 결과 (또는 --patch를 주면 전체 변경 내용)\n\n저장소 상태는 전혀 바꾸지 않는다.",
		"gk ask":                      "git/gk 관련 질문에 현재 저장소 상황을 반영해 이해하기 쉬운 답변 생성. 실제 브랜치명, 커밋 식별값, 파일명을 넣은 예시로 설명하고 관련 gk 명령 제안.\n\nAI 서비스(프로바이더) 선택 순서:\n  1. --provider 옵션\n  2. .gk.yaml의 ai.provider 설정\n  3. 자동 감지 (nvidia → gemini → qwen → kiro-cli)\n\n예시:\n  gk ask \"rebase와 merge의 차이점은?\"\n  gk ask \"현재 브랜치에서 main으로 어떻게 머지하나요?\"\n  gk ask \"마지막 커밋을 취소하려면?\"\n  gk ask \"How does gk sync work?\" --provider anthropic --lang ko",
		"gk do":                       "평소 말하듯 입력한 내용을 분석해 git/gk 명령 묶음을 만들고, 사용자 확인 후 차례로 실행.\n\n기본은 실제 실행 없이 미리보기만 보여주며, 확인(y/Enter)하면 실행. 되돌리기 어려운 위험한 명령(강제 push, 변경분 버리는 hard reset 등)은 한 번 더 확인.\n\nAI 서비스(프로바이더) 선택 순서:\n  1. --provider 옵션\n  2. .gk.yaml의 ai.provider 설정\n  3. 자동 감지 (nvidia → gemini → qwen → kiro-cli)\n\n예시:\n  gk do \"이 브랜치를 main에 리베이스해줘\"\n  gk do \"어제 커밋 취소\" --yes\n  gk do \"feature/auth 브랜치 만들고 체크아웃\" --dry-run\n  gk do \"rename this branch to feature/login\" --json",
		"gk explain":                  "에러 메시지를 분석해 원인, 해결 방법, 예방 팁 제시. --last 옵션을 쓰면 마지막 실행 명령을 단계별로 설명.\n\nAI 서비스(프로바이더) 선택 순서:\n  1. --provider 옵션\n  2. .gk.yaml의 ai.provider 설정\n  3. 자동 감지 (nvidia → gemini → qwen → kiro-cli)\n\n예시:\n  gk explain \"fatal: not a git repository\"\n  gk explain \"error: failed to push some refs\"\n  gk explain --last\n  gk explain \"merge conflict\" --provider anthropic --lang ko",
		"gk pr":                       "현재 브랜치와 기준(base) 브랜치 사이의 변경 내용을 비교하고, 커밋 메시지를 모아 AI 서비스의 요약 기능으로 정돈된 PR(코드 변경 요청) 설명문 생성.\n\n기준 브랜치는 설정값(base_branch)을 따르거나 자동 감지(main/master). 결과는 기본적으로 화면에 출력되며, --output clipboard를 쓰면 클립보드에 바로 복사.",
		"gk review":                   "기본적으로 커밋 직전 단계에 올려둔(staged) 변경 내용을 AI 서비스의 요약 기능으로 검토. 또는 특정 구간을 지정해 검토.\n\n기본은 staged 변경분(git diff --cached)을 검토. --range로 \"ref1..ref2\" 같은 구간을 지정하거나, --base <브랜치>로 브랜치 전체(그 브랜치에서 갈라져 나온 시점 이후 전부)를 검토할 수 있음 — 갈라진 지점(merge-base) 기준이라 기준 브랜치에 새로 쌓인 커밋은 검토에 섞이지 않음. 출력은 기본적으로 일반 텍스트이며, --format json을 쓰면 구조화된 형식으로 출력.",
		"gk changelog":                "두 지점(ref) 사이의 커밋을 모아 AI 서비스의 요약 기능으로 변경 이력(changelog) 생성.\n\n기본적으로 --from은 가장 최근 태그(git describe --tags --abbrev=0), --to는 현재 위치(HEAD). 출력은 기본적으로 Markdown이며, --format json을 쓰면 구조화된 형식으로 출력.",
		"gk doctor":                   "저장소나 시스템을 건드리지 않는 점검을 모아 실행하고, PASS/WARN/FAIL 결과와 함께 복사해서 바로 쓸 수 있는 해결 안내 출력. gk 설치 후 처음 실행하기 좋은 명령.\n\n또한 흔히 겪는 \"git이 index를 못 쓰는\" 상황과 \"rebase 도중에 멈춰 꼼짝 못 하는\" 상황을 잡아내는 저장소 상태 진단 포함:\n  - 남아 있는 .git/index.lock 잠금 파일\n  - 진행 중인 rebase/merge/cherry-pick/bisect 작업\n  - 병합이 끝나지 않은 파일(unmerged paths)\n\n--fix를 쓰면 발견된 항목을 하나씩 짚으며 그 자리에서 고칠지 물어봄. --verbose나 --ai를 쓰면 선택 사항인 AI 연동(anthropic/openai/nvidia/groq API 키, gemini/qwen/kiro-cli 실행 파일)도 함께 점검.\n\n종료 코드:\n  0  FAIL 항목 없음\n  1  FAIL 항목 하나 이상",
		"gk lint-commit":              "하나 이상의 커밋 메시지가 Conventional Commits 규칙에 맞는지 점검.\n\n사용 방식:\n  gk lint-commit                    — 마지막 커밋(HEAD)\n  gk lint-commit HEAD~3..HEAD       — 지정한 커밋 구간\n  gk lint-commit --file <경로>      — 파일에 담긴 메시지 하나 (commit-msg 훅용)\n  gk lint-commit --staged           — .git/COMMIT_EDITMSG 파일을 읽어 점검",
		"gk preflight":                "cfg.preflight.steps에 적힌 검사 단계들을 순서대로 실행. 각 단계는 셸 명령이거나 다음 내장 별칭 중 하나:\n\n내장 별칭:\n  commit-lint   — 가장 최근 커밋 메시지가 Conventional Commits 규칙에 맞는지 검사\n  branch-check  — 현재 브랜치 이름이 설정된 형식에 맞는지 검사\n  no-conflict   — 기준(base) 브랜치와 합칠 때 충돌이 날지 미리 확인",
		"gk guard":                    "저장소에 등록된 모든 정책 규칙을 검사해 위반 사항을 보여줌. 규칙은 .gk.yaml의 policies: 항목에 정의. v0.9 MVP에는 secret_patterns 규칙이 포함(gitleaks가 설치돼 있으면 동작). gitleaks가 없으면 이 규칙은 아무 동작도 하지 않고 실패 대신 안내 메모만 출력.",
		"gk guard check":              "등록된 모든 규칙을 동시에 검사하고, 위반 사항을 심각도 순(오류 → 경고 → 안내)으로 출력. 종료 코드:\n\n  0 — 위반 없음, 또는 안내 수준만 있음\n  1 — 경고가 하나 이상 있음\n  2 — 오류가 하나 이상 있음",
		"gk guard init":               "저장소 최상위 폴더(또는 --repo로 지정한 경로)에 .gk.yaml 파일을 생성. 규칙을 하나씩 켤 수 있도록 모든 항목이 주석 처리된 policies: 블록이 들어감.\n\n.gk.yaml이 이미 있으면 0이 아닌 종료 코드로 끝남. --force를 주면 덮어씀.",
		"gk init":                     "프로젝트를 분석해 .gitignore, .gk.yaml, AI 참고 파일(CLAUDE.md, AGENTS.md)을 한 번에 생성.\n\n--only로 일부만 생성, --dry-run으로 미리 보기, --force로 기존 파일 덮어쓰기.",
		"gk config init":              "지원하는 모든 설정 항목(ai, commit, log, status, branch, clone, worktree 등)을 설명하는 주석 가득한 YAML 설정 템플릿 파일 생성. 시작점으로 쓰는 용도 — 원하는 대로 고치고, 필요한 줄의 주석을 풀어서 사용. --out 없으면 $XDG_CONFIG_HOME/gk/config.yaml (없으면 ~/.config/gk/config.yaml)에 생성. 이미 파일이 있으면 --force 없이는 절대 덮어쓰지 않음.",
		"gk hooks":                    "gk를 실행하도록 .git/hooks/ 안에 연결 스크립트를 설치하거나 제거.\n\n  pre-commit  → gk guard check  (정책 검사: 비밀정보, 파일 크기 등)\n  commit-msg  → gk lint-commit  (커밋 메시지 규칙 검사)\n  pre-push    → gk preflight    (보내기 전 사전 검사 모음)\n\ngk가 설치한 hook에는 표시 주석이 붙음. 설치 프로그램은 그 표시가 없는 hook은 --force 없이는 덮어쓰지 않음(--force를 쓰면 시간 기록이 붙은 .bak 백업 파일도 함께 생성).",
		"gk land":                     "작업 마무리를 한 번에: 변경이 있으면 AI 커밋, 서버와 동기화(기준 브랜치 포함), 서버로 보내기까지 단계별로 실행. 실패하면 어느 단계인지와 되돌아갈 방법을 알려줌. cleanup 옵션은 합쳐진 브랜치 정리까지.",
		"gk context":                  "저장소 상태를 한 번에 파악: 현재 브랜치·원격 동기화(↑↓)·변경 개수·진행 중인 작업(rebase 등)·기준 브랜치 차이·worktree 목록·다음 할 일 제안. --json이면 AI 도구가 읽는 형식으로 출력.",
		"gk agents":                   "AI 에이전트 지침 파일(CLAUDE.md/AGENTS.md)에 gk 사용 규약 블록을 설치·점검. print(출력만)/install(설치·갱신)/check(버전 일치 확인). 블록 바깥 내용은 절대 건드리지 않음.",
		"gk ship":                     "배포(release)를 위한 마지막 점검 과정 실행: 배포 브랜치가 깨끗한지 확인, 다음 버전 태그(SemVer)를 자동 추론하거나 지정값 사용, 사전 검사 실행, 설명이 붙은 태그 생성, 브랜치와 태그를 함께 보냄(push). 태그를 보내면, 저장소에 태그 기반 배포 자동화가 설정된 경우 배포 작업이 시작됨.\n\n배포 파이프라인(설정 ship:): ship.watch는 태그를 보낸 뒤 실행되는 차단형 CI 추적 명령(예: gh run watch), ship.verify는 그 뒤의 사후 점검(산출물·tap 확인), ship.version_files는 버전 파일 목록을 직접 지정(자동 감지 대체). 모든 훅이 통과해야 완료 메시지가 출력됨. ship.wait: false(또는 --wait=false)는 push 직후 종료하고 건너뛴 watch/verify 명령을 출력함. ship.auto_confirm: true는 -y를 기본으로 만들며 --yes=false로 한 번만 되돌릴 수 있음.\n\nCHANGELOG의 [Unreleased]가 비어 있으면 커밋 내역에서 초안을 만들어 계획 화면에 미리 보여줌. 전역 --json을 --dry-run과 함께 쓰면 계획 전체를 JSON으로 출력(도구 연동용).",
		"gk update":                   "설치된 방식에 맞춰 gk를 스스로 최신 버전으로 업데이트.\n\n  brew      → 'brew upgrade x-mesh/tap/gk'로 넘김(바이너리가 Caskroom 아래에 있으면 'brew upgrade --cask x-mesh/tap/gk'; tap이 v0.55에서 formula에서 cask로 옮겨짐)\n  manual    → 최신 배포에서 맞는 압축 파일을 내려받아, 공개된 sha256 값으로 무결성 확인 후, 실행 중인 바이너리를 한 번에 교체. 설치 폴더에 쓰기 권한이 없으면(예: /usr/local/bin) sudo로 권한을 올림.\n  go-install → 그에 해당하는 'go install ...@latest' 명령을 출력.\n\n--check를 쓰면 내려받거나 업데이트하지 않고 버전만 비교.",
		"gk prompt-info":              "현재 작업 폴더(worktree)를 설명하는 짧은 표시를 출력. 셸 프롬프트에 끼워 넣는 용도.\n\n형식:\n\n  plain   (기본) 공백으로 구분된 토큰. 항상 연결된 worktree 표시로 시작(주 worktree에서는 비어 있음). --include 항목마다 토큰이 추가됨:\n\n             wt | wt:<이름>  연결된 worktree 표시\n             wip            HEAD 커밋 제목이 WIP 패턴과 일치\n             ±N             변경되거나 추적되지 않은 항목 N개\n             ↑N             upstream보다 커밋 N개 앞섬\n             ↓N             upstream보다 커밋 N개 뒤처짐\n             !<상태>        rebase/merge/cherry-pick/revert/bisect 진행 중\n\n  segment  git 저장소 안이면 \"<저장소>/<브랜치>\", 아니면 비어 있음. starship의 $directory + $git_branch를, 프로젝트와 브랜치를 한 번에 보여주는 중복 없는 한 개의 라벨로 대체하기 위한 형식.\n\n  json     구조화된 데이터(linked, repo, name, path, branch와 --include로 켠 선택 신호들). 자체 구획을 조합하는 프롬프트 프레임워크용.\n\n--include 항목은 선택 사항임 — 각각 프롬프트가 그려질 때마다 git 호출이 한 번씩 추가되기 때문. 필요한 것만 고를 것:\n\n  wip      git log -1 --format=%s     약 3ms\n  dirty    git status --porcelain     저장소 크기에 따라 5~50ms\n  ahead    git rev-list --count       약 5ms\n  behind   (ahead와 짝, 같은 호출)\n  state    .git/ 파일 상태 확인       거의 0\n\n연결된 worktree 여부는 git rev-parse --git-dir와 --git-common-dir 비교로 판단하며, 둘이 다르면 연결된 worktree임. --include가 없으면 이 두 호출만 하므로, 키를 누를 때마다 다시 그려지는 프롬프트에서 불러도 안전.\n\n예시:\n\n  # zsh 프롬프트 — worktree + WIP + 변경 개수 표시\n  function gk_info() {\n      local info=$(gk prompt-info --include=wip,dirty,ahead 2>/dev/null)\n      [[ -n \"$info\" ]] && print -n \" %F{yellow}[$info]%f\"\n  }\n\n  # starship: 사용자 정의 명령 구획 설정\n  [custom.gk_info]\n  command = \"gk prompt-info --include=wip,dirty,ahead,behind,state\"\n  when = \"gk prompt-info\"",
	}
	easyFlagKO = map[string]string{
		"gk status --ai":                     "현재 상태와 안전하게 할 수 있는 다음 작업을 AI가 설명",
		"gk status --exit-code":              "결과를 종료 코드로 알림: 0 깨끗함, 1 변경 있음, 2 하위 모듈만 변경됨, 3 충돌 있음, 4 원격보다 뒤처짐",
		"gk status --explain-base":           "기준 브랜치(base)가 어떻게 정해졌는지 출처·불일치·조치 안내를 여러 줄로 설명",
		"gk status --fetch":                  "앞섰는지/뒤처졌는지(↑N ↓N) 알리기 전에 현재 브랜치의 원격 변경을 먼저 가져옴(기본은 네트워크 사용 안 함, 직접 켜야 함)",
		"gk status --fetch-default":          "--explain-base와 함께 쓸 때 원격의 실제 기본 브랜치도 한 번 조회(네트워크 1회 사용)",
		"gk status --lang":                   "AI 상태 설명 언어 바꾸기(en|ko|...)",
		"gk status --legend":                 "현재 출력의 모든 기호와 색의 의미를 한 번 보여주고 종료",
		"gk status --provider":               "--ai에 쓸 AI 제공자(ai.provider) 바꾸기",
		"gk status --top":                    "목록을 앞에서 N개만 표시, 0이면 전부 표시. 숨겨진 나머지 개수는 맨 아래에 표시",
		"gk status --verbose":                "상태 요약을 더 자세히 표시, 반복하면 진단용 상세 정보까지 표시",
		"gk status --vis":                    "시각화 항목 선택(쉼표나 반복 지정): gauge,bar,progress,types,staleness,tree,conflict,churn,risk,base,since-push,stash,heatmap,glyphs, 'none'이면 기본 시각화 끔",
		"gk status --watch":                  "중단할 때까지 상태를 계속 새로고침",
		"gk status --watch-interval":         "--watch의 새로고침 간격(기본 2초)",
		"gk status --xy-style":               "각 항목의 상태 칸 표시 방식: 'labels'(new/mod/staged/conflict, 기본), 'glyphs'(+ ~ ● ⚔ #), 'raw'(git 원본 두 글자 코드 ??/.M/UU)",
		"gk commit --abort":                  "가장 최근 ai-commit 백업 지점으로 HEAD를 되돌리고 종료",
		"gk commit --allow-secret-kind":      "지정한 종류의 비밀정보 경고 무시(반복 지정 가능; 특수값 'all'은 모든 경고를 무시하고 커밋 강행)",
		"gk commit --ci":                     "CI 모드 — --force 또는 --dry-run 필수, 사용자에게 묻지 않음",
		"gk commit --dry-run":                "묶음 계획과 예상 토큰 비용 미리보기, AI 호출 안 함",
		"gk commit --force":                  "대화형 검토 없이 바로 커밋",
		"gk commit --force-wip":              "일부 커밋이 이미 원격에 올라간 경우라도 WIP 묶음을 풀어 정리(이미 올라간 기록을 다시 쓰므로 이후 강제 푸시 필요)",
		"gk commit --include-unstaged":       "준비 안 된 변경과 새 파일도 포함(기본 켜짐)",
		"gk commit --include-noise":          "보통 제외하는 빌드·의존성·캐시 파일(node_modules, __pycache__, *.db 등)도 포함 — .gitignore 가드 건너뜀",
		"gk commit --lang":                   "메시지 언어(ai.lang) 바꾸기(en|ko|...)",
		"gk commit --model":                  "이번 실행에만 쓸 모델 바꾸기(HTTP 제공자만 해당)",
		"gk commit --no-verify":              "노이즈·비밀정보 커밋 가드와 privacy gate 임계값을 함께 건너뛰기(무시된 비밀정보는 보고 후 git 기록에 포함됨 — 실제 자격증명이면 즉시 폐기·재발급; 원격 AI로 보내는 payload의 redaction은 유지)",
		"gk commit --no-wip-unwrap":          "HEAD 줄기에서 WIP 성격 커밋 감지·정리 건너뛰기",
		"gk commit --provider":               "AI 제공자(ai.provider) 바꾸기(gemini|qwen|kiro)",
		"gk commit --staged-only":            "이미 준비된(staged) 변경만 대상으로 함",
		"gk commit --yes":                    "모든 확인에 자동 동의(터미널이 아닐 때 --force와 같음)",
		"gk push --from":                     "현재 체크아웃과 무관하게 지정한 브랜치를 푸시(gk merge --into의 짝). 예: 다른 워크트리에서 main에 머지한 뒤 gk push --from main",
		"gk push --force":                    "기록이 어긋나도 푸시 허용(--force-with-lease 사용, 안전 강제 푸시)",
		"gk push --no-verify":                "비밀정보 패턴 검사 건너뛰기(--skip-scan과 동일; 'gk commit -n'과 일관)",
		"gk push --skip-scan":                "비밀정보 패턴 검사 건너뛰기",
		"gk push --yes":                      "확인 절차 건너뛰기(자동화용)",
		"gk pull --autostash":                "합치기 전에 작업 중 변경을 임시 보관(stash)하고 끝난 뒤 다시 꺼냄",
		"gk pull --base":                     "기준 브랜치 지정(비우면 자동 감지)",
		"gk pull --fetch-only":               "가져오기만 하고 합치지는 않음",
		"gk pull --merge":                    "--strategy merge 줄임말(기록이 갈라졌을 때 병합 진행에 대한 명시적 동의 역할도 함)",
		"gk pull --no-rebase":                "--fetch-only의 옛 이름(권장하지 않음)",
		"gk pull --rebase":                   "--strategy rebase 줄임말(기록이 갈라졌을 때 재정렬 진행에 대한 명시적 동의 역할도 함)",
		"gk pull --strategy":                 "합치는 방식: rebase|merge|ff-only|auto",
		"gk pull --verbose":                  "원격·방식·합치기 세부 정보 표시, 반복하면 진단 정보까지 표시",
		"gk pull --with-base":                "기준 브랜치(main 등)도 함께 최신으로 빨리 감기(체크아웃 없이, 안전하지 않으면 건너뜀)",
		"gk sync --autostash":                "합치기 전에 작업 중 변경을 임시 보관(stash)하고 끝난 뒤 다시 꺼냄",
		"gk sync --base":                     "기준 브랜치 지정(비우면 자동 감지)",
		"gk sync --fetch":                    "합치기 전에 <remote>/<base>를 가져와 로컬 <base>를 빨리 감기",
		"gk sync --fetch-only":               "<remote>/<base>를 가져와 로컬 <base>만 빨리 감기, 합치기는 건너뜀",
		"gk sync --no-fetch":                 "권장하지 않음: 이제 기본이 네트워크 미사용이라 아무 동작 없는 옛 이름으로만 남음",
		"gk sync --strategy":                 "합치는 방식: rebase|merge|ff-only|auto",
		"gk sync --upstream-only":            "옛 v0.6 동작: 현재 브랜치를 origin/<자기 브랜치>로만 빨리 감기(권장하지 않음, v0.8에서 제거)",
		"gk switch --create":                 "주어진 이름으로 새 브랜치를 만든 뒤 그 브랜치로 이동",
		"gk switch --detach":                 "브랜치로 이동하지 않고 해당 지점에 HEAD만 분리해 둠",
		"gk switch --develop":                "develop/dev 브랜치로 이동",
		"gk switch --fetch":                  "이동 전에 원격 브랜치 정보를 새로고침",
		"gk switch --force":                  "로컬 변경을 버림(git switch --discard-changes)",
		"gk switch --main":                   "감지된 main/master 브랜치로 이동",
		"gk log --body":                      "각 커밋의 메시지 본문을 제목 아래 들여써서 표시(릴리스 노트·상세 설명)",
		"gk log --calendar":                  "로그 위에 주별·요일별 활동 열지도(heatmap) 표시",
		"gk log --cc":                        "각 커밋 앞에 Conventional Commits 기호를 붙이고 뒤에 종류별 집계 추가",
		"gk log --format":                    "git pretty-format 형식 문자열(설정값 덮어씀)",
		"gk log --full":                      "긴 제목을 터미널 너비에 맞춰 자르지 않음",
		"gk log --graph":                     "갈래(토폴로지) 그래프 포함",
		"gk log --hotspots":                  "저장소에서 가장 자주 바뀐 파일을 건드린 커밋 표시",
		"gk log --impact":                    "커밋별 변경량(추가+삭제)에 비례한 막대 추가",
		"gk log --lanes":                     "작성자별 레인(swim-lane)으로 표시(커밋 목록 대체)",
		"gk log --legend":                    "현재 출력의 모든 기호와 색의 의미를 한 번 보여주고 종료",
		"gk log --limit":                     "최대 커밋 개수(0이면 무제한)",
		"gk log --pulse":                     "로그 위에 커밋 리듬 스파크라인 표시",
		"gk log --safety":                    "각 커밋 앞에 재정렬(rebase) 안전도 표시 추가(◆/◇/✎/!)",
		"gk log --since":                     "지정한 시점 이후의 커밋만 표시(예: 1w, 2d, \"last monday\")",
		"gk log --tags-rule":                 "태그가 붙은 커밋 앞마다 구분선 삽입",
		"gk log --trailers":                  "Co-authored-by/Reviewed-by 같은 trailer 정보 모아서 추가",
		"gk log --vis":                       "시각화 묶음 선택(설정 기본값 덮어씀, 'none'이면 끔): pulse,calendar,tags-rule,impact,cc,safety,hotspots,trailers,lanes,body",
		"gk diff --conflicts":                "병합 충돌 표시가 있는 부분만 보여줌(작업 내용 비교에서만 동작)",
		"gk diff --context":                  "변경 부분 주변에 함께 보여줄 줄 수(기본 3)",
		"gk diff --interactive":              "파일을 직접 넘겨가며 보는 대화형 탐색 모드",
		"gk diff --no-pager":                 "페이저(긴 출력 넘겨보기) 끄기",
		"gk diff --no-ref-labels":            "파일 헤더 아래 ◀/▶ 비교 대상 라벨 끄기",
		"gk diff --no-word-diff":             "단어 단위 하이라이트 끄기",
		"gk diff --digest":                   "패치 본문 없이 요약만: 파일별 변경 종류·줄 수·바뀐 함수 이름 목록. 코드 리뷰 전에 \"어디가 바뀌었나\" 한눈에 보기",
		"gk diff --staged":                   "준비된(staged) 변경 표시",
		"gk diff --stat":                     "변경 통계 요약 표시",
		"gk merge --autostash":               "합치기 전에 추적 중인 변경 사항을 임시 보관(stash)했다가 끝난 뒤 되돌림",
		"gk merge --ff-only":                 "기록을 새로 만들지 않고 그대로 앞당기는 방식(fast-forward)만 허용",
		"gk merge --into":                    "현재 브랜치(소스)를 지정한 브랜치의 작업 폴더(worktree)에 합침",
		"gk merge --no-ai":                   "합치기 계획 요약 생략",
		"gk merge --no-commit":               "합치기는 진행하되 기록 만들기(커밋) 직전에 멈춤",
		"gk merge --no-ff":                   "그대로 앞당길 수 있을 때에도 합침 기록(merge commit)을 따로 만듦",
		"gk merge --plan-only":               "실제 git merge는 돌리지 않고 합치기 계획만 출력",
		"gk merge --provider":                "합치기 계획에 쓰는 ai.provider 설정을 덮어씀",
		"gk merge --skip-precheck":           "충돌 사전 점검(merge-tree) 생략",
		"gk merge --squash":                  "합침 기록(merge commit)을 만들지 않고 대상의 변경 사항을 하나로 합쳐 가져옴",
		"gk next --lang":                     "안내 언어 설정을 덮어씀 (en|ko|...)",
		"gk next --provider":                 "ai.provider 설정을 덮어씀",
		"gk next --run":                      "확인을 거친 뒤 추천된 다음 단계를 실행",
		"gk continue --yes":                  "물어보지 않고 바로 이어서 진행",
		"gk abort --yes":                     "물어보지 않고 바로 취소",
		"gk branch list --gone":              "원격에서 삭제되어 연결이 끊긴 브랜치만 보여줌",
		"gk branch list --merged":            "기준 브랜치(base)에 이미 합쳐진 브랜치만 보여줌",
		"gk branch list --stale":             "마지막 기록이 N일보다 오래된 브랜치만 보여줌 (0이면 전체)",
		"gk branch list --unmerged":          "기준 브랜치(base)에 아직 합쳐지지 않은 브랜치만 보여줌",
		"gk branch clean --all":              "합쳐진 것, 연결 끊긴 것, 오래된 것, 합쳐 가져온(squash-merged) 브랜치를 모두 포함",
		"gk branch clean --dry-run":          "실제로 지우지 않고 무엇이 지워질지만 보여줌",
		"gk branch clean --force":            "git branch -D로 강제 삭제",
		"gk branch clean --gone":             "합쳐진 브랜치 대신, 원격에서 삭제되어 연결이 끊긴 브랜치를 대상으로 함",
		"gk branch clean --include-remote":   "원격에만 있는 브랜치도 후보에 포함 (git push --delete로 삭제)",
		"gk branch clean --no-ai":            "AI 분석 끔",
		"gk branch clean --remote":           "git remote prune 실행",
		"gk branch clean --squash-merged":    "하나로 합쳐 가져온(squash-merged) 브랜치 포함",
		"gk branch clean --stale":            "마지막 기록이 N일보다 오래된 브랜치 포함",
		"gk branch clean --worktrees":        "작업 폴더(worktree)에 체크아웃된 브랜치도 삭제 (먼저 깨끗한 작업 폴더를 제거하며, 변경 사항이 남은 폴더는 건너뜀)",
		"gk branch clean --yes":              "화면 확인 절차 건너뜀",
		"gk branch-check --branch":           "현재 브랜치 대신 지정한 이름을 검사",
		"gk branch-check --patterns":         "검사용 정규식 패턴을 직접 지정(쉼표로 구분)",
		"gk branch-check --quiet":            "출력을 숨기고 종료 코드로만 결과 판단",
		"gk worktree --global":               "모든 프로젝트에 걸쳐 gk가 관리하는 모든 worktree를 나열(TUI 안에서는 'g' 키로 켜고 끔)",
		"gk worktree --print-path":           "'cd' 시 새 셸로 들어가는 대신 선택한 경로를 출력(cd $(gk wt --print-path) 형태의 셸 래퍼용)",
		"gk worktree add --detach":           "worktree에서 브랜치를 따라가지 않고 현재 위치(HEAD)에서 분리",
		"gk worktree add --from":             "새 브랜치를 만들 기준 지점(기본값: HEAD)",
		"gk worktree add --new":              "[branch] 이름의 새 브랜치를 --from 지점에서 생성",
		"gk worktree remove --force":         "worktree에 저장 안 한 변경이 있거나 잠겨 있어도 강제로 삭제",
		"gk resolve --ai":                    "모든 충돌을 AI로 해결 (--strategy ai 의 단축)",
		"gk resolve --dry-run":               "파일을 바꾸지 않고 해결 결과 미리보기만 표시",
		"gk resolve --no-ai":                 "AI 분석 사용 안 함",
		"gk resolve --no-backup":             ".orig 백업 파일 생성 건너뛰기",
		"gk resolve --strategy":              "모든 충돌에 적용할 방식 지정: ours(내 쪽), theirs(상대 쪽), ai",
		"gk precheck --base":                 "합치는 기준점을 직접 지정(기본 자동 계산 기준점을 대신함)",
		"gk precheck --json":                 "프로그램이 읽기 쉬운 JSON 형식으로 출력",
		"gk rebase --plan":                   "실행할 계획서(JSON): 파일 경로 또는 '-'(표준 입력)",
		"gk rebase --plan-template":          "지금 범위의 커밋 목록을 계획서 초안(JSON)으로 출력하고 종료",
		"gk rebase --onto":                   "정리 범위의 기준점(기본: 연결된 원격 브랜치, 없으면 원격 기준 브랜치)",
		"gk rebase --allow-pushed":           "서버에 이미 올라간 커밋의 재작성을 허용(이후 강제 push 필요)",
		"gk edit-conflict --editor":          "$EDITOR 대신 사용할 편집기 지정",
		"gk edit-conflict --list":            "편집기를 열지 않고 충돌 파일 목록만 출력",
		"gk reset --clean":                   "'git clean -fd'도 함께 실행해 추적되지 않는 파일까지 삭제",
		"gk reset --dry-run":                 "실제로 되돌리지 않고 어떤 일이 일어날지만 출력",
		"gk reset --remote":                  "내용을 받아올 원격 저장소 (기본: config.remote / origin)",
		"gk reset --to":                      "되돌릴 목표 위치 지정(예: origin/main). 기본은 현재 브랜치에 연결된 원격",
		"gk reset --to-remote":               "설정된 연결 원격을 무시하고 <원격>/<현재 브랜치> 상태로 되돌리기",
		"gk reset --yes":                     "확인 절차 건너뛰기",
		"gk refresh --no-fetch":              "원격에서 받아오기를 건너뛰고, 이미 저장된 원격 정보로 빨리감기",
		"gk clone --https":                   "이번 실행에서 https 주소로 강제 (clone.default_protocol 설정을 덮어씀)",
		"gk clone --ssh":                     "이번 실행에서 ssh 주소로 강제 (clone.default_protocol 설정을 덮어씀)",
		"gk stash push --include-untracked":  "아직 git이 추적하지 않는 새 파일도 함께 임시 보관(stash)에 넣음 (기본값: 켜짐)",
		"gk stash push --message":            "임시 보관(stash)에 붙일 설명",
		"gk wipe --dry-run":                  "실제로 비우지 않고 무엇이 지워질지만 보여줌",
		"gk wipe --include-ignored":          ".gitignore로 무시되던 파일까지 함께 삭제",
		"gk wipe --yes":                      "확인 절차를 건너뛰고 바로 진행",
		"gk forget --analyze":                "실제로 지우지 않고, 대상별로 차지하는 파일 개수와 총 용량만 보고(--dry-run 자동 적용)",
		"gk forget --bar":                    "--analyze와 함께 쓸 때 막대그래프 표시 방식: auto|filled|block|none (auto는 화면에서는 채움, 파이프 출력에서는 없음) (기본값 \"auto\")",
		"gk forget --depth":                  "--analyze에 대상을 지정하지 않았을 때, 경로 앞 N단계 기준으로 묶어서 보기 (0이면 파일 단위) (기본값 1)",
		"gk forget --engine":                 "기록 재작성 방식: native(기본, gk 내장 — 설치 불필요, 브랜치·태그만 재작성하고 백업은 그대로 둠) 또는 filter-repo(git filter-repo에 위임, 별도 설치 필요). .gk.yaml의 forget.engine으로도 지정 가능 (기본값 \"native\")",
		"gk forget --force-dirty":            "지우려는 대상 밖에 저장 안 한 변경이 있어도 그대로 진행(그 변경은 filter-repo가 되돌려 사라짐)",
		"gk forget --interactive":            "--analyze와 함께 쓸 때 점검 결과를 여러 개 골라 선택 화면을 열고, 고른 경로를 지움",
		"gk forget --keep":                   "지우는 대상에서 제외할 경로 패턴(filepath.Match 형식, 여러 번 사용 가능)",
		"gk forget --sort":                   "--analyze와 함께 쓸 때 정렬 기준: size|churn|name (churn은 고유 파일 개수순, 다시 쓰기 부담이 큰 경로가 드러남) (기본값 \"size\")",
		"gk forget --top":                    "--analyze에 대상을 지정하지 않았을 때, 저장소 전체 점검을 용량 큰 N개로 제한 (기본값 20)",
		"gk forget --yes":                    "진행 여부를 묻는 확인 질문 건너뛰기",
		"gk undo --hard":                     "현재 작업 중인 변경을 버리고, 고른 시점 그대로 복원(위험)",
		"gk undo --limit":                    "보여줄 작업 기록(reflog) 최대 개수 (기본값 20)",
		"gk undo --list":                     "작업 기록만 출력하고, 묻거나 되돌리지 않음",
		"gk undo --to":                       "선택 화면 없이 특정 지점으로 바로 되돌리기(예: HEAD@{3})",
		"gk undo --yes":                      "확인 질문 건너뛰기",
		"gk restore --limit":                 "보여줄 항목 최대 개수 (기본값 20)",
		"gk restore --lost":                  "git fsck --lost-found로 찾은, 어디에도 연결되지 않은 커밋/파일 보기",
		"gk timemachine list --all-branches": "모든 로컬 브랜치의 작업 기록 포함 (기본값: 현재 위치 HEAD만)",
		"gk timemachine list --branch":       "특정 브랜치 하나(또는 'HEAD')로만 거르기. 작업 기록과 백업 모두에 적용",
		"gk timemachine list --dangling-cap": "어디에도 연결되지 않은 커밋을 훑어볼 최대 개수 (0이면 제한 없음. git fsck는 객체 수에 비례해 느려짐) (기본값 500)",
		"gk timemachine list --json":         "NDJSON으로 출력(한 줄에 항목 하나)",
		"gk timemachine list --kinds":        "보여줄 종류를 쉼표로 구분: reflog, backup, stash, dangling (기본값 \"reflog,backup\")",
		"gk timemachine list --limit":        "최대 항목 수 (0이면 제한 없음) (기본값 50)",
		"gk timemachine list --since":        "(지금 - 기간) 이후의 항목만 거르기, 예: 24h. 7d 형식은 지원 안 함 — 168h처럼 시간 단위로 쓸 것",
		"gk timemachine list-backups --json": "NDJSON으로 출력(한 줄에 항목 하나)",
		"gk timemachine list-backups --kind": "종류로 거르기: undo, wipe, timemachine",
		"gk timemachine restore --autostash": "되돌리기 전에 작업 중 변경을 잠시 따로 보관(stash)했다가, 끝난 뒤 다시 꺼내기",
		"gk timemachine restore --dry-run":   "실제 실행 없이 계획만 출력",
		"gk timemachine restore --force":     "작업 중 변경이 있어도 hard 방식 허용(저장 안 한 변경 사라짐)",
		"gk timemachine restore --mode":      "되돌리는 방식: soft, mixed, hard, auto 중 하나 (기본값 \"auto\")",
		"gk timemachine show --patch":        "요약 대신 전체 변경 내용 보기",
		"gk ask --help":                      "ask 명령 도움말 표시",
		"gk ask --lang":                      "출력 언어 지정 (en|ko|...)",
		"gk ask --model":                     "이번 실행에만 쓸 AI 모델 지정 (HTTP 방식 AI 서비스 전용)",
		"gk ask --provider":                  "사용할 AI 서비스 지정 (anthropic|openai|nvidia|gemini|groq|qwen|kiro)",
		"gk do --dry-run":                    "실행 계획만 보여주고 실제로는 실행 안 함",
		"gk do --force":                      "모든 확인 건너뜀 (위험한 명령 포함)",
		"gk do --help":                       "do 명령 도움말 표시",
		"gk do --json":                       "JSON 형식으로 출력",
		"gk do --lang":                       "출력 언어 지정 (en|ko|...)",
		"gk do --model":                      "이번 실행에만 쓸 AI 모델 지정 (HTTP 방식 AI 서비스 전용)",
		"gk do --provider":                   "사용할 AI 서비스 지정 (anthropic|openai|nvidia|gemini|groq|qwen|kiro)",
		"gk do --yes":                        "일반 확인 건너뜀 (위험한 명령은 그래도 확인)",
		"gk explain --help":                  "explain 명령 도움말 표시",
		"gk explain --lang":                  "출력 언어 지정 (en|ko|...)",
		"gk explain --last":                  "마지막에 실행한 명령을 단계별로 설명",
		"gk explain --model":                 "이번 실행에만 쓸 AI 모델 지정 (HTTP 방식 AI 서비스 전용)",
		"gk explain --provider":              "사용할 AI 서비스 지정 (anthropic|openai|nvidia|gemini|groq|qwen|kiro)",
		"gk pr --dry-run":                    "AI 서비스를 호출하지 않고 보낼 요청 내용만 보여줌",
		"gk pr --help":                       "pr 명령 도움말 표시",
		"gk pr --lang":                       "설정된 출력 언어(ai.lang) 대신 이번에만 지정 (en|ko|...)",
		"gk pr --output":                     "결과를 내보낼 곳: \"stdout\"(화면) 또는 \"clipboard\"(클립보드) (기본값 \"stdout\")",
		"gk pr --provider":                   "설정된 AI 서비스(ai.provider) 대신 이번에만 지정",
		"gk review --base":                   "지정한 <브랜치>에서 갈라져 나온 시점 이후의 브랜치 전체 변경을 검토",
		"gk review --dry-run":                "AI 서비스를 호출하지 않고 보낼 요청 내용만 보여줌",
		"gk review --format":                 "출력 형식: \"text\"(기본) 또는 \"json\" (기본값 \"text\")",
		"gk review --help":                   "review 명령 도움말 표시",
		"gk review --provider":               "설정된 AI 서비스(ai.provider) 대신 이번에만 지정",
		"gk review --range":                  "검토할 구간 지정 (예: \"main..HEAD\"); 기본값은 staged 변경분",
		"gk changelog --dry-run":             "AI 서비스를 호출하지 않고 보낼 요청 내용만 보여줌",
		"gk changelog --format":              "출력 형식: \"markdown\"(기본) 또는 \"json\" (기본값 \"markdown\")",
		"gk changelog --from":                "시작 지점 (기본값: 가장 최근 태그)",
		"gk changelog --help":                "changelog 명령 도움말 표시",
		"gk changelog --model":               "이번 실행에만 쓸 AI 모델 지정 (HTTP 방식 AI 서비스 전용)",
		"gk changelog --provider":            "설정된 AI 서비스(ai.provider) 대신 이번에만 지정",
		"gk changelog --to":                  "끝 지점 (기본값: 현재 위치 HEAD)",
		"gk doctor --ai":                     "선택 사항인 AI 서비스 진단도 함께 포함",
		"gk doctor --fix":                    "점검 후 발견된 항목을 하나씩 짚으며 고칠지 물어봄",
		"gk doctor --help":                   "doctor 명령 도움말 표시",
		"gk doctor --json":                   "기계가 읽을 수 있는 JSON 형식으로 출력",
		"gk lint-commit --file":              "<경로>에 저장된 메시지 하나를 점검",
		"gk lint-commit --help":              "lint-commit 명령 도움말 표시",
		"gk lint-commit --staged":            "커밋 준비된 .git/COMMIT_EDITMSG 메시지를 점검",
		"gk preflight --continue-on-failure": "한 단계가 실패해도 멈추지 않고 계속 진행",
		"gk preflight --dry-run":             "실제로 실행하지 않고 어떤 단계를 거치는지만 출력",
		"gk preflight --skip":                "건너뛸 단계 이름(쉼표로 구분)",
		"gk guard check --json":              "위반 사항을 한 줄에 하나씩 NDJSON 형식으로 출력(스크립트 처리용)",
		"gk guard init --force":              "기존 .gk.yaml을 덮어씀",
		"gk guard init --out":                "<repo>/.gk.yaml 대신 지정한 경로에 파일 생성",
		"gk init --force":                    "기존 파일을 합치지 않고 덮어씀",
		"gk init --kiro":                     ".kiro/steering/ 문서도 함께 생성",
		"gk init --only":                     "지정한 대상만 생성(gitignore, config, ai 중 하나)",
		"gk config init --force":             "이미 있는 파일도 덮어쓰기",
		"gk config init --out":               "기본 위치 대신 지정한 경로에 파일 생성",
		"gk hooks install --all":             "gk가 아는 모든 hook 설치",
		"gk hooks install --commit-msg":      "commit-msg hook 설치",
		"gk hooks install --force":           "gk 것이 아닌 hook도 덮어쓰기(먼저 .bak 백업 생성)",
		"gk hooks install --pre-commit":      "pre-commit hook 설치(gk guard check)",
		"gk hooks install --pre-push":        "pre-push hook 설치",
		"gk hooks uninstall --all":           "gk가 설치한 모든 hook 제거",
		"gk hooks uninstall --commit-msg":    "commit-msg hook 제거",
		"gk hooks uninstall --pre-commit":    "pre-commit hook 제거",
		"gk hooks uninstall --pre-push":      "pre-push hook 제거",
		"gk ship --allow-dirty":              "저장하지 않은 변경이 남아 있어도 배포 허용",
		"gk ship --allow-non-base":           "기준 브랜치가 아닌 곳에서도 배포 태그 허용",
		"gk ship --dry-run":                  "실제로 태그를 만들거나 보내지 않고 배포 계획만 출력",
		"gk ship --major":                    "최신 태그의 주(major) 버전을 1 올림",
		"gk ship --minor":                    "최신 태그의 부(minor) 버전을 1 올림",
		"gk ship --no-fetch":                 "미리 하는 git fetch --tags를 건너뜀(오래된 로컬 정보 사용)",
		"gk ship --no-release":               "배포 태그를 만들거나 보내지 않고 브랜치만 보냄",
		"gk ship --no-verify":                "push 전 비밀정보 패턴 검사 건너뛰기('gk commit -n' / 'gk push -n'과 일관)",
		"gk ship --patch":                    "최신 태그의 수(patch) 버전을 1 올림",
		"gk ship --push":                     "브랜치와 배포 태그를 보냄(기본 켜짐)",
		"gk ship --skip-preflight":           "설정된 사전 검사를 건너뜀",
		"gk ship --version":                  "태그로 쓸 배포 버전(앞의 v는 붙여도 되고 안 붙여도 됨)",
		"gk ship --wait":                     "태그를 보낸 뒤 watch/verify 파이프라인을 실행(기본 켜짐). --wait=false면 push 직후 종료(설정: ship.wait)",
		"gk ship --yes":                      "마지막 확인 질문을 건너뜀(설정: ship.auto_confirm)",
		"gk update --check":                  "업데이트는 하지 않고 새 버전이 있는지만 알려줌. 최신이면 0, 더 새 버전이 있으면 1로 종료",
		"gk update --force":                  "이미 최신 버전이어도 다시 설치",
		"gk update --to":                     "특정 태그로 고정(manual 설치에서만); 기본값은 최신 배포",
		"gk prompt-info --format":            "출력 형식: plain|segment|json (기본값 \"plain\")",
		"gk prompt-info --include":           "쉼표로 구분한 선택 신호: wip,dirty,ahead,behind,state",
	}
}
